  
--Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY gender;
--Q2. Which customers used a discount but still  spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount > (select AVG(purchase_amount) from customer);

--Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5 item_purchased, ROUND(AVG(review_rating),2) AS average_rating
from customer
GROUP BY item_purchased 
ORDER BY average_rating DESC

--Q4. Compare the average Purchase Amounts between Standard and Expres Shipping
SELECT shipping_type, AVG(purchase_amount) as average_purchase_amount
FROM customer
GROUP BY shipping_type
HAVING shipping_type IN ('Standard' , 'Express');

--Q4. Compare the average Purchase Amounts between Standard and Expres Shipping
SELECT shipping_type, ROUND(AVG(purchase_amount),2) as average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type;

--Q5. Do subscribed customer spend more? Compare average spend and total revenue between subcribers and non-subscribers?
SELECT subscription_status,COUNT(customer_id) as total_customer, CAST(AVG(CAST(purchase_amount AS decimal(10,2))) AS decimal(10,2)) AS average_spend , SUM(purchase_amount) as total_revenue
FROM customer
GROUP BY subscription_status;

--Q6. Which 5 products have the highest percentage of purchases with discount applied?
--products were purchased more with discount
SELECT  TOP 5
item_purchased, ROUND(100*SUM(CASE WHEN discount_applied ='Yes' Then 1 ELSE 0 END)/COUNT(discount_applied),2) as discount_rate
FROM customer
Group by item_purchased
ORDER BY discount_rate DESC;

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases
--and show the count of each segment
with customer_type as (
SELECT customer_id,previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
	ELSE 'Loyal'
END AS customer_loyalty_segment
FROM customer)

select customer_loyalty_segment, count(*) 
FROM customer_type
GROUP BY customer_loyalty_segment;



--Q8. What are the top 3 most purchased products within each category?

SELECT category, item_purchased
FROM customer
GROUP BY category, item_purchased;
----------------------------------
with item_counts as (
SELECT category,
item_purchased,
COUNT(customer_id) as total_orders,-- or COUNT(*)
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC ) as item_rank
--ROW_NUMBER(), ties rank will get in order 1,2
from customer
GROUP BY category, item_purchased)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank<=3;
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
COUNT(customer_id) as repeat_buyers
FROM customer
WHERE previous_purchases > 5 
GROUP BY subscription_status

--Q10. What is the revenue contribution (total revenue) of each age group?

SELECT age_group,
sum(purchase_amount) as total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;

select *
from customer